feat: add longbow_recording_fuzzy.csv download

diff --git a/.github/actions/install-mqtt-simulator/action.yml b/.github/actions/install-mqtt-simulator/action.yml
--- a/.github/actions/install-mqtt-simulator/action.yml
+++ b/.github/actions/install-mqtt-simulator/action.yml
@@ -49,3 +49,18 @@ runs:
           echo "Error: Failed to download mqtt_pub" >&2
           exit 1
         fi
+        CSV_DL_URL="https://tdenginetestdata.blob.core.windows.net/test-data/longbow_recording_fuzzy.csv.tar.gz"
+        OUTPUT_FILE="/opt/longbow_recording_fuzzy.csv"
+        if [ -f "$OUTPUT_FILE" ]; then
+            echo "mqtt csv already exists, skipping download."
+            return 0
+        fi
+
+        if ! wget -O "${OUTPUT_FILE}.tar.gz" "$CSV_DL_URL"; then
+            echo "::error ::Failed to download mqtt csv from $CSV_DL_URL"
+            exit 1
+        fi
+
+        echo "Successfully downloaded mqtt csv."
+
+        cd /opt &&  tar -xvf /opt/longbow_recording_fuzzy.csv.tar.gz
