test:alter labels

diff --git a/.github/workflows/run-coverage-tests-on-linux.yml b/.github/workflows/run-coverage-tests-on-linux.yml
--- a/.github/workflows/run-coverage-tests-on-linux.yml
+++ b/.github/workflows/run-coverage-tests-on-linux.yml
@@ -86,52 +86,52 @@ jobs:
           fi
           git pull || { echo "Failed to pull the latest code."; exit 1; }
 
-      - name: Update submodule
-        run: |
-          cd ${{ env.WKC }}
-          git submodule update --init --recursive
+      # - name: Update submodule
+      #   run: |
+      #     cd ${{ env.WKC }}
+      #     git submodule update --init --recursive
  
-      - name: Build docker container
-        run: |
-          date
-          rm -rf ${{ env.WKC }}/debug
-          cd ${{ env.WKC }}/tests/parallel_test
-          time ./container_build_coverage.sh -w ${{ env.WKDIR }} -e
+      # - name: Build docker container
+      #   run: |
+      #     date
+      #     rm -rf ${{ env.WKC }}/debug
+      #     cd ${{ env.WKC }}/tests/parallel_test
+      #     time ./container_build_coverage.sh -w ${{ env.WKDIR }} -e
 
-      - name: Get parameters for testing
-        id: get_param
-        run: |
-          log_server_file="/home/log_server.json"
-          timeout_cmd=""
-          extra_param=""
+      # - name: Get parameters for testing
+      #   id: get_param
+      #   run: |
+      #     log_server_file="/home/log_server.json"
+      #     timeout_cmd=""
+      #     extra_param=""
 
-          if [ -f "$log_server_file" ]; then
-            log_server_enabled=$(jq '.enabled' "$log_server_file")
-            timeout_param=$(jq '.timeout' "$log_server_file")
-            if [ "$timeout_param" != "null" ] && [ "$timeout_param" != "0" ]; then
-              timeout_cmd="timeout $timeout_param"
-            fi
+      #     if [ -f "$log_server_file" ]; then
+      #       log_server_enabled=$(jq '.enabled' "$log_server_file")
+      #       timeout_param=$(jq '.timeout' "$log_server_file")
+      #       if [ "$timeout_param" != "null" ] && [ "$timeout_param" != "0" ]; then
+      #         timeout_cmd="timeout $timeout_param"
+      #       fi
 
-            if [ "$log_server_enabled" == "1" ]; then
-              log_server=$(jq '.server' "$log_server_file" | sed 's/\\\"//g')
-              if [ "$log_server" != "null" ] && [ "$log_server" != "" ]; then
-                extra_param="-w $log_server"
-              fi
-            fi
-          fi
-          echo "timeout_cmd=$timeout_cmd" >> $GITHUB_OUTPUT
-          echo "extra_param=$extra_param" >> $GITHUB_OUTPUT
+      #       if [ "$log_server_enabled" == "1" ]; then
+      #         log_server=$(jq '.server' "$log_server_file" | sed 's/\\\"//g')
+      #         if [ "$log_server" != "null" ] && [ "$log_server" != "" ]; then
+      #           extra_param="-w $log_server"
+      #         fi
+      #       fi
+      #     fi
+      #     echo "timeout_cmd=$timeout_cmd" >> $GITHUB_OUTPUT
+      #     echo "extra_param=$extra_param" >> $GITHUB_OUTPUT
 
-      - name: Run function test cases
-        run: |
-          cd ${{ env.WKC }}/tests/parallel_test
-          export DEFAULT_RETRY_TIME=1
-          date
-          chmod +x ${{ env.WKC }}/tests/parallel_test/run.sh
-          ${{ steps.get_param.outputs.timeout_cmd }} time ./run.sh -e -m /home/m.json -t cases.task -b PR-${{ github.run_number }} -l ${{ env.WKDIR }}/log -o 1200 ${{ steps.get_param.outputs.extra_param }} || true
-          ${{ steps.get_param.outputs.timeout_cmd }} time ./run.sh -e -m /home/m.json -t longtimeruning_cases.task -b PR-${{ github.run_number }} -l ${{ env.WKDIR }}/log -o 300 ${{ steps.get_param.outputs.extra_param }} || true
-          #${{ steps.get_param.outputs.timeout_cmd }} time ./run.sh -e -m /home/m.json -t tdgpt_cases.task -b PR-${{ github.run_number }} -l ${{ env.WKDIR }}/log -o 1200 ${{ steps.get_param.outputs.extra_param }} || true
-        continue-on-error: true  
+      # - name: Run function test cases
+      #   run: |
+      #     cd ${{ env.WKC }}/tests/parallel_test
+      #     export DEFAULT_RETRY_TIME=1
+      #     date
+      #     chmod +x ${{ env.WKC }}/tests/parallel_test/run.sh
+      #     ${{ steps.get_param.outputs.timeout_cmd }} time ./run.sh -e -m /home/m.json -t cases.task -b PR-${{ github.run_number }} -l ${{ env.WKDIR }}/log -o 1200 ${{ steps.get_param.outputs.extra_param }} || true
+      #     ${{ steps.get_param.outputs.timeout_cmd }} time ./run.sh -e -m /home/m.json -t longtimeruning_cases.task -b PR-${{ github.run_number }} -l ${{ env.WKDIR }}/log -o 300 ${{ steps.get_param.outputs.extra_param }} || true
+      #     #${{ steps.get_param.outputs.timeout_cmd }} time ./run.sh -e -m /home/m.json -t tdgpt_cases.task -b PR-${{ github.run_number }} -l ${{ env.WKDIR }}/log -o 1200 ${{ steps.get_param.outputs.extra_param }} || true
+      #   continue-on-error: true  
    
       - name: Run taosd && taosc coverage 
         if: always() 
