test:pull new code

diff --git a/.github/workflows/run-coverage-tests-on-linux.yml b/.github/workflows/run-coverage-tests-on-linux.yml
--- a/.github/workflows/run-coverage-tests-on-linux.yml
+++ b/.github/workflows/run-coverage-tests-on-linux.yml
@@ -58,7 +58,7 @@ jobs:
           echo "Preparing TDinternal repository..."
           cd ${{ env.WK }}
           git reset --hard
-          git clean -fd
+          git clean -f
           git remote prune origin
           git fetch
           if git rev-parse --verify origin/${{ env.SOURCE_BRANCH_TDINTERNAL }} >/dev/null 2>&1; then
@@ -67,9 +67,9 @@ jobs:
             echo "Branch ${{ env.SOURCE_BRANCH_TDINTERNAL }} does not exist. Switching to default branch cover/3.0."
             git switch -c cover/3.0 origin/cover/3.0
           fi
-          echo "Pulling latest code from 3.0 branch..."
+          echo "Pulling latest code from cover/3.0 branch..."
           git pull || { echo "Failed to pull the latest code."; exit 1; }
-          git pull origin 3.0 || { echo "Failed to pull from 3.0 branch"; exit 1; }
+          #git pull origin 3.0 || { echo "Failed to pull from 3.0 branch"; exit 1; }
           echo "Current branch: $(git branch --show-current)"
           echo "Current commit:" && git log -1 --oneline  
 
@@ -78,7 +78,7 @@ jobs:
           echo "Preparing TDengine repository..."
           cd ${{ env.WKC }}
           git reset --hard
-          git clean -fd
+          git clean -f
           git remote prune origin
           git fetch
           if git rev-parse --verify origin/${{ env.SOURCE_BRANCH_TDENGINE }} >/dev/null 2>&1; then
@@ -87,9 +87,9 @@ jobs:
             echo "Branch ${{ env.SOURCE_BRANCH_TDENGINE }} does not exist. Switching to default branch cover/3.0."
             git switch -c cover/3.0 origin/cover/3.0
           fi
-          echo "Pulling latest code from 3.0 branch..."
+          echo "Pulling latest code from cover/3.0 branch..."
           git pull || { echo "Failed to pull the latest code."; exit 1; }
-          git pull origin 3.0 || { echo "Failed to pull from 3.0 branch"; exit 1; }
+          #git pull origin 3.0 || { echo "Failed to pull from 3.0 branch"; exit 1; }
           echo "Current branch: $(git branch --show-current)"
           echo "Current commit:" && git log -1 --oneline  
 
