test:add cov 2

diff --git a/.github/workflows/run-coverage-tests-on-linux.yml b/.github/workflows/run-coverage-tests-on-linux.yml
--- a/.github/workflows/run-coverage-tests-on-linux.yml
+++ b/.github/workflows/run-coverage-tests-on-linux.yml
@@ -151,23 +151,23 @@ jobs:
           echo "::endgroup::"
         continue-on-error: true
 
-      - name: Run taosd && taosc coverage 2
-        if: always() 
-        run: |
-          echo "::group::Run taosd && taosc coverage"
-          cd ${{ env.WKC }}/tests/parallel_test
-          echo "Running coverage script at $(date)"
-          chmod +x ${{ env.WKC }}/tests/parallel_test/run_coverage_container_2.sh
-          ./run_coverage_container_2.sh -d ${{ env.WKDIR }} -b ${{ env.SOURCE_BRANCH_TDENGINE }} > coverage.log 2>&1
-          if [ $? -ne 0 ]; then
-              echo "Coverage script failed. Check coverage.log for details."
-          fi
-          echo "Coverage log line count:"
-          cat coverage.log | wc -l
-          echo "Filtered coverage log (excluding specific patterns):"
-          cat coverage.log | grep -v FN | grep -v DA | grep -v SF | grep -v LF | grep -v TN | grep -v end | grep -v LH || true
-          echo "::endgroup::"
-        continue-on-error: true
+      # - name: Run taosd && taosc coverage 2
+      #   if: always() 
+      #   run: |
+      #     echo "::group::Run taosd && taosc coverage"
+      #     cd ${{ env.WKC }}/tests/parallel_test
+      #     echo "Running coverage script at $(date)"
+      #     chmod +x ${{ env.WKC }}/tests/parallel_test/run_coverage_container_2.sh
+      #     ./run_coverage_container_2.sh -d ${{ env.WKDIR }} -b ${{ env.SOURCE_BRANCH_TDENGINE }} > coverage.log 2>&1
+      #     if [ $? -ne 0 ]; then
+      #         echo "Coverage script failed. Check coverage.log for details."
+      #     fi
+      #     echo "Coverage log line count:"
+      #     cat coverage.log | wc -l
+      #     echo "Filtered coverage log (excluding specific patterns):"
+      #     cat coverage.log | grep -v FN | grep -v DA | grep -v SF | grep -v LF | grep -v TN | grep -v end | grep -v LH || true
+      #     echo "::endgroup::"
+      #   continue-on-error: true
 
       - name: Clearup the running cases
         if: always()
